import java.util.HashMap;

public class NYCLocations {
	HashMap<String, String> NYCTLCLocations = new HashMap<String, String>();
	
	public String translate(String string) {
		String location = NYCTLCLocations.get(string);
		return location;
	}
	public void createHashMap() {
    NYCTLCLocations.put("1","EWR:Newark Airport");
	NYCTLCLocations.put("2","Queens:Jamaica Bay");
    NYCTLCLocations.put("3","Bronx:Allerton-Pelham Gardens");
	NYCTLCLocations.put("4","Manhattan:Alphabet City");
	NYCTLCLocations.put("5","Staten Island:Arden Heights");
	NYCTLCLocations.put("6","Staten Island:Arrochar-Fort Wadsworth");
	NYCTLCLocations.put("7","Queens:Astoria");
    NYCTLCLocations.put("8","Queens:Astoria Park");
    NYCTLCLocations.put("9","Queens:Auburndale");
    NYCTLCLocations.put("10","Queens:Baisley Park");
    NYCTLCLocations.put("11","Brooklyn:Bath Beach");
    NYCTLCLocations.put("12","Manhattan:Battery Park");
    NYCTLCLocations.put("13","Manhattan:Battery Park City");
    NYCTLCLocations.put("14","Brooklyn:Bay Ridge");
    NYCTLCLocations.put("15","Queens:Bay Terrace-Fort Totten");
    NYCTLCLocations.put("16","Queens:Bayside");
    NYCTLCLocations.put("17","Brooklyn:Bedford");
    NYCTLCLocations.put("18","Bronx:Bedford Park");
    NYCTLCLocations.put("19","Queens:Bellerose");
    NYCTLCLocations.put("20","Bronx:Belmont");
    NYCTLCLocations.put("21","Brooklyn:Bensonhurst East");
    NYCTLCLocations.put("22","Brooklyn:Bensonhurst West");
    NYCTLCLocations.put("23","Staten Island:Bloomfield-Emerson Hill");
    NYCTLCLocations.put("24","Manhattan:Bloomingdale");
    NYCTLCLocations.put("25","Brooklyn:Boerum Hill");
    NYCTLCLocations.put("26","Brooklyn:Borough Park");
    NYCTLCLocations.put("27","Queens:Breezy Point-Fort Tilden-Riis Beach");
    NYCTLCLocations.put("28","Queens:Briarwood-Jamaica Hills");
    NYCTLCLocations.put("29","Brooklyn:Brighton Beach");
    NYCTLCLocations.put("30","Queens:Broad Channel");
    NYCTLCLocations.put("31","Bronx:Bronx Park");
    NYCTLCLocations.put("32","Bronx:Bronxdale");
    NYCTLCLocations.put("33","Brooklyn:Brooklyn Heights");
    NYCTLCLocations.put("34","Brooklyn:Brooklyn Navy Yard");
    NYCTLCLocations.put("35","Brooklyn:Brownsville");
    NYCTLCLocations.put("36","Brooklyn:Bushwick North");
    NYCTLCLocations.put("37","Brooklyn:Bushwick South");
    NYCTLCLocations.put("38","Queens:Cambria Heights");
    NYCTLCLocations.put("39","Brooklyn:Canarsie");
    NYCTLCLocations.put("40","Brooklyn:Carroll Gardens");
    NYCTLCLocations.put("41","Manhattan:Central Harlem");
    NYCTLCLocations.put("42","Manhattan:Central Harlem North");
    NYCTLCLocations.put("43","Manhattan:Central Park");
    NYCTLCLocations.put("44","Staten Island:Charleston-Tottenville");
    NYCTLCLocations.put("45","Manhattan:Chinatown");
    NYCTLCLocations.put("46","Bronx:City Island");
    NYCTLCLocations.put("47","Bronx:Claremont-Bathgate");
    NYCTLCLocations.put("48","Manhattan:Clinton East");
    NYCTLCLocations.put("49","Brooklyn:Clinton Hill");
    NYCTLCLocations.put("50","Manhattan:Clinton West");
    NYCTLCLocations.put("51","Bronx:Co-Op City");
    NYCTLCLocations.put("52","Brooklyn:Cobble Hill");
    NYCTLCLocations.put("53","Queens:College Point");
    NYCTLCLocations.put("54","Brooklyn:Columbia Street");
    NYCTLCLocations.put("55","Brooklyn:Coney Island");
    NYCTLCLocations.put("56","Queens:Corona");
    NYCTLCLocations.put("57","Queens:Corona");
    NYCTLCLocations.put("58","Bronx:Country Club");
    NYCTLCLocations.put("59","Bronx:Crotona Park");
    NYCTLCLocations.put("60","Bronx:Crotona Park East");
    NYCTLCLocations.put("61","Brooklyn:Crown Heights North");
    NYCTLCLocations.put("62","Brooklyn:Crown Heights South");
    NYCTLCLocations.put("63","Brooklyn:Cypress Hills");
    NYCTLCLocations.put("64","Queens:Douglaston");
    NYCTLCLocations.put("65","Brooklyn:Downtown Brooklyn-MetroTech");
    NYCTLCLocations.put("66","Brooklyn:DUMBO-Vinegar Hill");
    NYCTLCLocations.put("67","Brooklyn:Dyker Heights");
    NYCTLCLocations.put("68","Manhattan:East Chelsea");
    NYCTLCLocations.put("69","Bronx:East Concourse-Concourse Village");
    NYCTLCLocations.put("70","Queens:East Elmhurst");
    NYCTLCLocations.put("71","Brooklyn:East Flatbush-Farragut");
    NYCTLCLocations.put("72","Brooklyn:East Flatbush-Remsen Village");
    NYCTLCLocations.put("73","Queens:East Flushing");
    NYCTLCLocations.put("74","Manhattan:East Harlem North");
    NYCTLCLocations.put("75","Manhattan:East Harlem South");
    NYCTLCLocations.put("76","Brooklyn:East New York");
    NYCTLCLocations.put("77","Brooklyn:East New York-Pennsylvania Avenue");
    NYCTLCLocations.put("78","Bronx:East Tremont");
    NYCTLCLocations.put("79","Manhattan:East Village");
    NYCTLCLocations.put("80","Brooklyn:East Williamsburg");
    NYCTLCLocations.put("81","Bronx:Eastchester");
    NYCTLCLocations.put("82","Queens:Elmhurst");
    NYCTLCLocations.put("83","Queens:Elmhurst-Maspeth");
    NYCTLCLocations.put("84","Staten Island:Eltingville-Annadale-Princes Bay");
    NYCTLCLocations.put("85","Brooklyn:Erasmus");
    NYCTLCLocations.put("86","Queens:Far Rockaway");
    NYCTLCLocations.put("87","Manhattan:Financial District North");
    NYCTLCLocations.put("88","Manhattan:Financial District South");
    NYCTLCLocations.put("89","Brooklyn:Flatbush-Ditmas Park");
    NYCTLCLocations.put("90","Manhattan:Flatiron");
    NYCTLCLocations.put("91","Brooklyn:Flatlands");
    NYCTLCLocations.put("92","Queens:Flushing");
    NYCTLCLocations.put("93","Queens:Flushing Meadows-Corona Park");
    NYCTLCLocations.put("94","Bronx:Fordham South");
    NYCTLCLocations.put("95","Queens:Forest Hills");
    NYCTLCLocations.put("96","Queens:Forest Park-Highland Park");
    NYCTLCLocations.put("97","Brooklyn:Fort Greene");
    NYCTLCLocations.put("98","Queens:Fresh Meadows");
    NYCTLCLocations.put("99","Staten Island:Freshkills Park");
    NYCTLCLocations.put("100","Manhattan:Garment District");
    NYCTLCLocations.put("101","Queens:Glen Oaks");
    NYCTLCLocations.put("102","Queens:Glendale");
    NYCTLCLocations.put("103","Manhattan:Governors Island-Ellis Island-Liberty Island");
    NYCTLCLocations.put("104","Manhattan:Governors Island-Ellis Island-Liberty Island");
    NYCTLCLocations.put("105","Manhattan:Governors Island-Ellis Island-Liberty Island");
    NYCTLCLocations.put("106","Brooklyn:Gowanus");
    NYCTLCLocations.put("107","Manhattan:Gramercy");
    NYCTLCLocations.put("108","Brooklyn:Gravesend");
    NYCTLCLocations.put("109","Staten Island:Great Kills");
    NYCTLCLocations.put("110","Staten Island:Great Kills Park");
    NYCTLCLocations.put("111","Brooklyn:Green-Wood Cemetery");
    NYCTLCLocations.put("112","Brooklyn:Greenpoint");
    NYCTLCLocations.put("113","Manhattan:Greenwich Village North");
    NYCTLCLocations.put("114","Manhattan:Greenwich Village South");
    NYCTLCLocations.put("115","Staten Island:Grymes Hill-Clifton");
    NYCTLCLocations.put("116","Manhattan:Hamilton Heights");
    NYCTLCLocations.put("117","Queens:Hammels-Arverne");
    NYCTLCLocations.put("118","Staten Island:Heartland Village-Todt Hill");
    NYCTLCLocations.put("119","Bronx:Highbridge");
    NYCTLCLocations.put("120","Manhattan:Highbridge Park");
    NYCTLCLocations.put("121","Queens:Hillcrest-Pomonok");
    NYCTLCLocations.put("122","Queens:Hollis");
    NYCTLCLocations.put("123","Brooklyn:Homecrest");
    NYCTLCLocations.put("124","Queens:Howard Beach");
    NYCTLCLocations.put("125","Manhattan:Hudson Sq");
    NYCTLCLocations.put("126","Bronx:Hunts Point");
    NYCTLCLocations.put("127","Manhattan:Inwood");
    NYCTLCLocations.put("128","Manhattan:Inwood Hill Park");
    NYCTLCLocations.put("129","Queens:Jackson Heights");
    NYCTLCLocations.put("130","Queens:Jamaica");
    NYCTLCLocations.put("131","Queens:Jamaica Estates");
    NYCTLCLocations.put("132","Queens:JFK Airport");
    NYCTLCLocations.put("133","Brooklyn:Kensington");
    NYCTLCLocations.put("134","Queens:Kew Gardens");
    NYCTLCLocations.put("135","Queens:Kew Gardens Hills");
    NYCTLCLocations.put("136","Bronx:Kingsbridge Heights");
    NYCTLCLocations.put("137","Manhattan:Kips Bay");
    NYCTLCLocations.put("138","Queens:LaGuardia Airport");
    NYCTLCLocations.put("139","Queens:Laurelton");
    NYCTLCLocations.put("140","Manhattan:Lenox Hill East");
    NYCTLCLocations.put("141","Manhattan:Lenox Hill West");
    NYCTLCLocations.put("142","Manhattan:Lincoln Square East");
    NYCTLCLocations.put("143","Manhattan:Lincoln Square West");
    NYCTLCLocations.put("144","Manhattan:Little Italy-NoLiTa");
    NYCTLCLocations.put("145","Queens:Long Island City-Hunters Point");
    NYCTLCLocations.put("146","Queens:Long Island City-Queens Plaza");
    NYCTLCLocations.put("147","Bronx:Longwood");
    NYCTLCLocations.put("148","Manhattan:Lower East Side");
    NYCTLCLocations.put("149","Brooklyn:Madison");
    NYCTLCLocations.put("150","Brooklyn:Manhattan Beach");
    NYCTLCLocations.put("151","Manhattan:Manhattan Valley");
    NYCTLCLocations.put("152","Manhattan:Manhattanville");
    NYCTLCLocations.put("153","Manhattan:Marble Hill");
    NYCTLCLocations.put("154","Brooklyn:Marine Park-Floyd Bennett Field");
    NYCTLCLocations.put("155","Brooklyn:Marine Park-Mill Basin");
    NYCTLCLocations.put("156","Staten Island:Mariners Harbor");
    NYCTLCLocations.put("157","Queens:Maspeth");
    NYCTLCLocations.put("158","Manhattan:Meatpacking-West Village West");
    NYCTLCLocations.put("159","Bronx:Melrose South");
    NYCTLCLocations.put("160","Queens:Middle Village");
    NYCTLCLocations.put("161","Manhattan:Midtown Center");
    NYCTLCLocations.put("162","Manhattan:Midtown East");
    NYCTLCLocations.put("163","Manhattan:Midtown North");
    NYCTLCLocations.put("164","Manhattan:Midtown South");
    NYCTLCLocations.put("165","Brooklyn:Midwood");
    NYCTLCLocations.put("166","Manhattan:Morningside Heights");
    NYCTLCLocations.put("167","Bronx:Morrisania-Melrose");
    NYCTLCLocations.put("168","Bronx:Mott Haven-Port Morris");
    NYCTLCLocations.put("169","Bronx:Mount Hope");
    NYCTLCLocations.put("170","Manhattan:Murray Hill");
    NYCTLCLocations.put("171","Queens:Murray Hill-Queens");
    NYCTLCLocations.put("172","Staten Island:New Dorp-Midland Beach");
    NYCTLCLocations.put("173","Queens:North Corona");
    NYCTLCLocations.put("174","Bronx:Norwood");
    NYCTLCLocations.put("175","Queens:Oakland Gardens");
    NYCTLCLocations.put("176","Staten Island:Oakwood");
    NYCTLCLocations.put("177","Brooklyn:Ocean Hill");
    NYCTLCLocations.put("178","Brooklyn:Ocean Parkway South");
    NYCTLCLocations.put("179","Queens:Old Astoria");
    NYCTLCLocations.put("180","Queens:Ozone Park");
    NYCTLCLocations.put("181","Brooklyn:Park Slope");
    NYCTLCLocations.put("182","Bronx:Parkchester");
    NYCTLCLocations.put("183","Bronx:Pelham Bay");
    NYCTLCLocations.put("184","Bronx:Pelham Bay Park");
    NYCTLCLocations.put("185","Bronx:Pelham Parkway");
    NYCTLCLocations.put("186","Manhattan:Penn Station-Madison Sq West");
    NYCTLCLocations.put("187","Staten Island:Port Richmond");
    NYCTLCLocations.put("188","Brooklyn:Prospect-Lefferts Gardens");
    NYCTLCLocations.put("189","Brooklyn:Prospect Heights");
    NYCTLCLocations.put("190","Brooklyn:Prospect Park");
    NYCTLCLocations.put("191","Queens:Queens Village");
    NYCTLCLocations.put("192","Queens:Queensboro Hill");
    NYCTLCLocations.put("193","Queens:Queensbridge-Ravenswood");
    NYCTLCLocations.put("194","Manhattan:Randalls Island");
    NYCTLCLocations.put("195","Brooklyn:Red Hook");
    NYCTLCLocations.put("196","Queens:Rego Park");
    NYCTLCLocations.put("197","Queens:Richmond Hill");
    NYCTLCLocations.put("198","Queens:Ridgewood");
    NYCTLCLocations.put("199","Bronx:Rikers Island");
    NYCTLCLocations.put("200","Bronx:Riverdale-North Riverdale-Fieldston");
    NYCTLCLocations.put("201","Queens:Rockaway Park");
    NYCTLCLocations.put("202","Manhattan:Roosevelt Island");
    NYCTLCLocations.put("203","Queens:Rosedale");
    NYCTLCLocations.put("204","Staten Island:Rossville-Woodrow");
    NYCTLCLocations.put("205","Queens:Saint Albans");
    NYCTLCLocations.put("206","Staten Island:Saint George-New Brighton");
    NYCTLCLocations.put("207","Queens:Saint Michaels Cemetery-Woodside");
    NYCTLCLocations.put("208","Bronx:Schuylerville-Edgewater Park");
    NYCTLCLocations.put("209","Manhattan:Seaport");
    NYCTLCLocations.put("210","Brooklyn:Sheepshead Bay");
    NYCTLCLocations.put("211","Manhattan:SoHo");
    NYCTLCLocations.put("212","Bronx:Soundview-Bruckner");
    NYCTLCLocations.put("213","Bronx:Soundview-Castle Hill");
    NYCTLCLocations.put("214","Staten Island:South Beach-Dongan Hills");
    NYCTLCLocations.put("215","Queens:South Jamaica");
    NYCTLCLocations.put("216","Queens:South Ozone Park");
    NYCTLCLocations.put("217","Brooklyn:South Williamsburg");
    NYCTLCLocations.put("218","Queens:Springfield Gardens North");
    NYCTLCLocations.put("219","Queens:Springfield Gardens South");
    NYCTLCLocations.put("220","Bronx:Spuyten Duyvil-Kingsbridge");
    NYCTLCLocations.put("221","Staten Island:Stapleton");
    NYCTLCLocations.put("222","Brooklyn:Starrett City");
    NYCTLCLocations.put("223","Queens:Steinway");
    NYCTLCLocations.put("224","Manhattan:Stuy Town-Peter Cooper Village");
    NYCTLCLocations.put("225","Brooklyn:Stuyvesant Heights");
    NYCTLCLocations.put("226","Queens:Sunnyside");
    NYCTLCLocations.put("227","Brooklyn:Sunset Park East");
    NYCTLCLocations.put("228","Brooklyn:Sunset Park West");
    NYCTLCLocations.put("229","Manhattan:Sutton Place-Turtle Bay North");
    NYCTLCLocations.put("230","Manhattan:Times Sq-Theatre District");
    NYCTLCLocations.put("231","Manhattan:TriBeCa-Civic Center");
    NYCTLCLocations.put("232","Manhattan:Two Bridges-Seward Park");
    NYCTLCLocations.put("233","Manhattan:UN-Turtle Bay South");
    NYCTLCLocations.put("234","Manhattan:Union Sq");
    NYCTLCLocations.put("235","Bronx:University Heights-Morris Heights");
    NYCTLCLocations.put("236","Manhattan:Upper East Side North");
    NYCTLCLocations.put("237","Manhattan:Upper East Side South");
    NYCTLCLocations.put("238","Manhattan:Upper West Side North");
    NYCTLCLocations.put("239","Manhattan:Upper West Side South");
    NYCTLCLocations.put("240","Bronx:Van Cortlandt Park");
    NYCTLCLocations.put("241","Bronx:Van Cortlandt Village");
    NYCTLCLocations.put("242","Bronx:Van Nest-Morris Park");
    NYCTLCLocations.put("243","Manhattan:Washington Heights North");
    NYCTLCLocations.put("244","Manhattan:Washington Heights South");
    NYCTLCLocations.put("245","Staten Island:West Brighton");
    NYCTLCLocations.put("246","Manhattan:West Chelsea-Hudson Yards");
    NYCTLCLocations.put("247","Bronx:West Concourse");
    NYCTLCLocations.put("248","Bronx:West Farms-Bronx River");
    NYCTLCLocations.put("249","Manhattan:West Village");
    NYCTLCLocations.put("250","Bronx:Westchester Village-Unionport");
    NYCTLCLocations.put("251","Staten Island:Westerleigh");
    NYCTLCLocations.put("252","Queens:Whitestone");
    NYCTLCLocations.put("253","Queens:Willets Point");
    NYCTLCLocations.put("254","Bronx:Williamsbridge-Olinville");
    NYCTLCLocations.put("255","Brooklyn:Williamsburg (North Side)");
    NYCTLCLocations.put("256","Brooklyn:Williamsburg (South Side)");
    NYCTLCLocations.put("257","Brooklyn:Windsor Terrace");
    NYCTLCLocations.put("258","Queens:Woodhaven");
    NYCTLCLocations.put("259","Bronx:Woodlawn-Wakefield");
    NYCTLCLocations.put("260","Queens:Woodside");
    NYCTLCLocations.put("261","Manhattan:World Trade Center");
    NYCTLCLocations.put("262","Manhattan:Yorkville East");
    NYCTLCLocations.put("263","Manhattan:Yorkville West");
	}
}
